#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Oct  2 16:20:06 2020

@author: fionafei
"""

import cvxpy as cp



x = cp.Variable(3, nonneg  = True) # vector variable


#obj_func=x[0]+2*x[1]
obj_func_neg=-2*x[0]-2*x[1]-4*x[2]

constraints = []
constraints.append(2*x[0]+x[1]+x[2]<=2)
constraints.append(3*x[0]+4*x[1]+2*x[2]>=8)
#constraints.append(x[0]<=3)


#problem = cp.Problem(cp.Maximize(obj_func), constraints)
problem = cp.Problem(cp.Minimize(obj_func_neg), constraints)

#problem.solve(solver=cp.CVXOPT,verbose = True)
#problem.solve(verbose = True)
problem.solve(solver=cp.GUROBI,verbose = True)

print("obj_func =")
#print(obj_func.value)
print(obj_func_neg.value)
print("x =")
print(x.value)
