#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Nov 14 11:18:50 2020

@author: fionafei
"""

import cvxpy as cp



x = cp.Variable((3,3), nonneg  = True) # vector variable


#obj_func=170*x[0]+220*x[1]+250*x[2]+55*x[3]
obj_func_neg=0*x[0,0]+0*x[0,1]+0*x[0,2]+0*x[1,0]+0*x[1,1]+0*x[1,2]+0*x[2,0]+0*x[2,1]+0*x[2,2]

constraints = []
constraints.append(x[0,0]>=0)
constraints.append(x[0,1]>=0)
constraints.append(x[0,2]>=0)
constraints.append(x[1,0]>=0)
constraints.append(x[1,1]>=0)
constraints.append(x[1,2]>=0)
constraints.append(x[2,0]>=0)
constraints.append(x[2,1]>=0)
constraints.append(x[2,2]>=0)

constraints.append(x[0,0]+x[1,0]+x[2,0]==7)
constraints.append(x[0,1]+x[1,1]+x[2,1]==7)
constraints.append(x[0,2]+x[1,2]+x[2,2]==7)

constraints.append(x[0,0]+x[0,1]+x[0,2]==7)
constraints.append(x[1,0]+x[1,1]+x[1,2]==7)
constraints.append(x[2,0]+x[2,1]+x[2,2]==7)

constraints.append(x[0,0]+x[0,1]/2==3.5)
constraints.append(x[1,0]+x[1,1]/2==3.5)
constraints.append(x[2,0]+x[2,1]/2==3.5)




#problem = cp.Problem(cp.Maximize(obj_func), constraints)
problem = cp.Problem(cp.Minimize(obj_func_neg), constraints)

#problem.solve(solver=cp.CVXOPT,verbose = True)
#problem.solve(verbose = True)
problem.solve(solver=cp.GUROBI,verbose = True)

print("obj_func =")
#print(obj_func.value)
print(obj_func_neg.value)
print("x =")
print(x.value)
