#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Dec  5 05:07:07 2020

@author: fionafei
"""


import cvxpy as cp

x = cp.Variable(3, nonneg = True) # vector variable



obj_func=3*x[0]-x[1]+6*x[2]
#obj_func_neg=3*x[0]+2*x[1]

constraints = []
constraints.append(5*x[0]+x[1]+4*x[2]<=42)
constraints.append(2*x[0]-x[1]+2*x[2]<=18)
constraints.append(x[0]>=0)
constraints.append(x[1]>=0)
constraints.append(x[2]>=0)


problem = cp.Problem(cp.Maximize(obj_func), constraints)
#problem = cp.Problem(cp.Minimize(obj_func_neg), constraints)

#problem.solve(solver=cp.CVXOPT,verbose = True)
#problem.solve(verbose = True)
problem.solve(solver=cp.GUROBI,verbose = True)

print("obj_func =")
print(obj_func.value)
#print(obj_func_neg.value)
print("x =")
print(x.value)

# Shadow prices or dual prices
print("optimal (x[0]+2*x[1]<=11) dual variable", constraints[0].dual_value)
print("optimal (x[0]-3*x[1]<=1) dual variable", constraints[1].dual_value)

print("optimal (x[0]>=0) dual variable", constraints[2].dual_value)
print("optimal (x[1]>=0) dual variable", constraints[3].dual_value)
print("optimal (x[2]>=0) dual variable", constraints[4].dual_value)