#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 27 22:27:41 2020

@author: fionafei
"""

import cvxpy as cp



x = cp.Variable(4, nonneg  = True) # vector variable


obj_func=170*x[0]+220*x[1]+250*x[2]+55*x[3]
#obj_func_neg=-2*x[0]-2*x[1]-4*x[2]

constraints = []
constraints.append(0.3*x[0]+0.24*x[1]+0.228*x[2]+0.1*x[3]<=4000)
constraints.append(x[0]-x[1]/0.8>=0)
constraints.append(x[0]-x[2]/0.76>=0)
constraints.append(x[0]>=25)
constraints.append(x[1]>=25)
constraints.append(x[2]>=25)
constraints.append(x[3]>=25)


problem = cp.Problem(cp.Maximize(obj_func), constraints)
#problem = cp.Problem(cp.Minimize(obj_func_neg), constraints)

#problem.solve(solver=cp.CVXOPT,verbose = True)
#problem.solve(verbose = True)
problem.solve(solver=cp.GUROBI,verbose = True)

print("obj_func =")
print(obj_func.value)
#print(obj_func_neg.value)
print("x =")
print(x.value)
